name: Add help-wanted issues to help wanted board

on:
  issues:
    types:
      - labeled

jobs:
  add-help-wanted:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        if: contains(github.event.label.name, 'help-wanted') || contains(github.event.label.name, 'sprintable')
        id: add-to-project
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/pyOpenSci/projects/3
          github-token: ${{ secrets.GHPROJECT_TOKEN }}
          labeled: help-wanted, sprintable
          label-operator: OR
